### ISSUE TITLE
Add minimal controls for arguments related to assets

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk-js#315]
By the time being, `lisk-js` relais on schema validations from `core`. Even though, we should implement minimal controls to ensure a proper argument processing inside the application.

I tag the issue as a bug because the application doesn't handle some exceptions properly. For example when using `createVote` with `delegates` argument as `null`. Below the output log:

```     
vote.createVote(account.password, null)

TypeError: Cannot read property 'join' of null
    at Object.isVoteTransaction (node_modules/lisk-js/dist-node/transactions/crypto.js:85:65)
    at getTransactionBytes (node_modules/lisk-js/dist-node/transactions/crypto.js:208:42)
    at createTransactionBuffer (node_modules/lisk-js/dist-node/transactions/crypto.js:339:35)
    at getBytes (node_modules/lisk-js/dist-node/transactions/crypto.js:357:9)
    at getHash (node_modules/lisk-js/dist-node/transactions/crypto.js:386:14)
    at Object.sign (node_modules/lisk-js/dist-node/transactions/crypto.js:410:13)
    at prepareTransaction (node_modules/lisk-js/dist-node/transactions/utils.js:32:31)
    at Object.createVote (node_modules/lisk-js/dist-node/transactions/vote.js:62:40)
```

**Comment by Tosch110** [comment]
This will be solved by https://github.com/LiskHQ/lisk-js/issues/417 so I am closing this issue
